### ISSUE TITLE
Issue with jekyll-compress removing closing body- and html-tag

### ISSUE THREAD

**Issue by olssonm** [penibelst/jekyll-compress-html#32] opened 2015-01-21 08:14 UTC
Been noticing that jekyll-compress removes the closing body and html-tag, which makes for pretty bad HTML.

Happens in two of my Jekyll projects, and I also checked out one of the repo-creators sites, "http://kleinfreund.de", and noticed the same issue there – missing `</body>` and `</html>`.

**Comment by olssonm** [comment] 2015-01-21 08:24
Oh, I see now this is perhaps per design? Seems like `</body>` and `<html>` really are optional, and I just double checked the endings-config. 

If so, feel free to close this issue =)

**Comment by kleinfreund** [comment] 2015-01-21 08:49
Yep, this is by design. See [jch.penibelst.de](http://jch.penibelst.de/), second point: <q>removes optional end tags</q>. Most of HTML’s elements don’t __require__ the end tag, but for the sake of their own sanity most devs include them anyway. It makes for nicer code.

**Comment by penibelst** [comment] 2015-01-21 08:50
The closing tags of `html` and `body` are optional. You can find them in the specs I linked to in the [documentation](http://jch.penibelst.de/).

**Closed by penibelst** 2015-01-21 08:50 UTC
